site_name: Cara
site_url: https://cara-lang.com/
site_author: Martin Janiczek (@janiczek)
site_description: Cara programming language
repo_url: https://github.com/cara-lang/compiler
copyright: "Made with 🧡 by Martin Janiczek"
edit_uri: https://github.com/cara-lang/website/edit/main/docs/
nav:
    - Home: index.md
    - Reference:
      - reference/index.md
      - Anonymous functions and holes: reference/anonymous-fns-and-holes.md
      - Tests: reference/tests.md
      - TODO Numbers: reference/numbers.md
      - TODO Booleans: reference/booleans.md
      - TODO Characters and strings: reference/chars-and-strings.md
      - TODO Collections: reference/collections.md
      - TODO Records: reference/records.md
      - TODO Tuples: reference/tuples.md
      - TODO Algebraic data types: reference/adts.md
      - TODO Functions: reference/fns.md
      - TODO Function overloading: reference/fn-overloading.md
      - TODO Type classes: reference/type-classes.md
      - TODO Type aliases: reference/type-aliases.md
      - TODO Type annotations: reference/type-annotations.md
      - TODO Standard library: reference/stdlib.md
      - TODO Operators: reference/operators.md
      - TODO Statements and blocks: reference/statements.md
      - TODO Where: reference/where.md
      - TODO Maybe and Result: reference/maybe-and-result.md
      - TODO Ranges: reference/ranges.md
      - TODO Pipelines: reference/pipelines.md
      - TODO Dot chaining: reference/dot.md
      - TODO Comments: reference/comments.md
      - TODO If expressions: reference/if.md
      - TODO Case expressions and pattern matching: reference/case.md
      - TODO Pattern guards: reference/guards.md
      - TODO Imports, exports and modules: reference/imports-exports-modules.md
      - TODO GADTs: reference/gadts.md
    - Principles:
      - principles/index.md
      - TODO Zen of Cara: principles/zen.md
      - TODO Functional programming: principles/fp.md
      - TODO Immutability: principles/immutability.md
      - TODO Purity and effects: principles/purity-and-effects.md
      - TODO Build modules around data structures: principles/build-modules-around-data-structures.md
      - TODO Make impossible states impossible: principles/make-impossible-states-impossible.md
      - TODO Common patterns:
        - principles/common-patterns/index.md
        - "TODO map: Functor": principles/common-patterns/functor.md
        - "TODO andMap, map2: Applicative": principles/common-patterns/applicative.md
        - "TODO orElse: Alternative": principles/common-patterns/alternative.md
        - "TODO concat: Semigroup": principles/common-patterns/semigroup.md
        - "TODO empty: Monoid": principles/common-patterns/monoid.md
        - "TODO andThen, flatMap: Monad": principles/common-patterns/monad.md
        - "TODO fold, reduce: Foldable": principles/common-patterns/foldable.md
        - "TODO sequence, traverse: Traversable": principles/common-patterns/traversable.md
    - Guides:
      - guides/index.md
      - TODO Cara for Elm developers: guides/cara-for-elm-devs.md
      - TODO Cara for Haskell developers: guides/cara-for-hs-devs.md
      - TODO Cara for JS/Python/Kotlin developers: guides/cara-for-js-py-kt-devs.md
      - TODO Working with ADTs: guides/adts.md
      - TODO Testing: guides/testing.md
      - TODO Performance and parallelism: guides/perf-and-parallelism.md
      - TODO Phantom types: guides/phantom-types.md
      - TODO Random data: guides/random-data.md
      - TODO Working with files: guides/files.md
    - Tutorials:
      - tutorials/index.md
      - TODO Getting started: tutorials/getting-started.md
      - TODO Scripting with Cara: tutorials/scripting.md
theme: 
  name: material
  icon:
    repo: fontawesome/brands/github
    logo: material/weather-sunset
  favicon: assets/images/favicon.png
  palette:
    primary: deep orange
  font:
    text: Rubik
    code: JetBrains Mono
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes 
    - navigation.top
    - navigation.expand
    - search.highlight
    - search.suggest
    - content.code.annotate 
    - content.tooltips
markdown_extensions:
  - admonition
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      guess_lang: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: false
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/cara-lang/compiler
      name: Compiler
    - icon: fontawesome/brands/github
      link: https://github.com/cara-lang/website
      name: Website
plugins:
  - search
  - typeset
  - privacy:
      external_links_attr_map:
        target: _blank
      external_links_noopener: true
  - minify:
      minify_html: true
# TODO try links in frontmatter for an automatic "Further reading" section
# ------- https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/#adding-related-links
# TODO try document contributors
# ------- https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#document-contributors
# TODO try card grids
# ------- https://squidfunk.github.io/mkdocs-material/reference/grids/#using-card-grids
# TODO try the blog? (*gulp*)
# ------- https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/
