site_name: Cara
site_url: https://cara-lang.com/
site_author: Martin Janiczek (@janiczek)
site_description: Cara programming language
repo_url: https://github.com/cara-lang/compiler
copyright: "Made with 🧡 by Martin Janiczek"
edit_uri: https://github.com/cara-lang/website/edit/main/docs/
nav:
    - Home: index.md
    - Reference:
      - reference/index.md
      - Basic types: reference/basic-types.md
      - Collections: reference/collections.md
      - Characters and strings: reference/chars-and-strings.md
      - Records: reference/records.md
      - Tuples: reference/tuples.md
      - Algebraic data types: reference/adts.md
      - Functions: reference/fns.md
      - Anonymous functions and holes: reference/anonymous-fns-and-holes.md
      - Function overloading: reference/fn-overloading.md
      - Type aliases: reference/type-aliases.md
      - Type annotations: reference/type-annotations.md
      - Standard library: reference/stdlib.md
      - Operators: reference/operators.md
      - Variables: reference/variables.md
      - Where: reference/where.md
      - Maybe: reference/maybe.md
      - Result: reference/result.md
      - Dot chaining: reference/dot.md
      - Comments: reference/comments.md
      - If expressions: reference/if.md
      - Case expressions and pattern matching: reference/case.md
      - Pattern guards: reference/guards.md
      - "Effect blocks and ! operator": reference/effect-blocks-and-bang.md
      - Imports, exports and modules: reference/imports-exports-modules.md
      - GADTs: reference/gadts.md
    - Principles:
      - principles/index.md
      - Zen of Cara: principles/zen.md
      - Functional programming: principles/fp.md
      - Immutability: principles/immutability.md
      - Purity and effects: principles/purity-and-effects.md
      - Build modules around data structures: principles/build-modules-around-data-structures.md
      - Make impossible states impossible: principles/make-impossible-states-impossible.md
      - Common patterns:
        - principles/common-patterns/index.md
        - "map: Functor": principles/common-patterns/functor.md
        - "andMap, map2: Applicative": principles/common-patterns/applicative.md
        - "orElse: Alternative": principles/common-patterns/alternative.md
        - "concat: Semigroup": principles/common-patterns/semigroup.md
        - "empty: Monoid": principles/common-patterns/monoid.md
        - "andThen, flatMap: Monad": principles/common-patterns/monad.md
        - "fold, reduce: Foldable": principles/common-patterns/foldable.md
        - "sequence, traverse: Traversable": principles/common-patterns/traversable.md
    - Guides:
      - guides/index.md
      - Cara for Elm developers: guides/cara-for-elm-devs.md
      - Cara for Haskell developers: guides/cara-for-hs-devs.md
      - Cara for JS/Python/Kotlin developers: guides/cara-for-js-py-kt-devs.md
      - Working with ADTs: guides/adts.md
      - Testing: guides/testing.md
      - Performance and parallelism: guides/perf-and-parallelism.md
      - Phantom types: guides/phantom-types.md
      - Random data: guides/random-data.md
    - Tutorials:
      - tutorials/index.md
      - Getting started: tutorials/getting-started.md
      - Scripting with Cara: tutorials/scripting.md
theme: 
  name: material
  icon:
    repo: fontawesome/brands/github
    logo: material/weather-sunset
  favicon: assets/images/favicon.png
  palette:
    primary: deep orange
  font:
    text: Rubik
    code: JetBrains Mono
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes 
    - navigation.top
    - navigation.expand
    - search.highlight
    - search.suggest
    - content.code.annotate 
    - content.tooltips
markdown_extensions:
  - abbr
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - admonition
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      guess_lang: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/cara-lang/compiler
      name: Compiler
    - icon: fontawesome/brands/github
      link: https://github.com/cara-lang/website
      name: Website
plugins:
  - search
  - typeset
  - privacy:
      external_links_attr_map:
        target: _blank
      external_links_noopener: true
# TODO try links in frontmatter for an automatic "Further reading" section
# ------- https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/#adding-related-links
# TODO try document contributors
# ------- https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#document-contributors
# TODO try card grids
# ------- https://squidfunk.github.io/mkdocs-material/reference/grids/#using-card-grids
# TODO try annotations
# ------- https://squidfunk.github.io/mkdocs-material/reference/annotations/#using-annotations
# TODO try page icons
# ------- https://squidfunk.github.io/mkdocs-material/reference/#setting-the-page-icon
# TODO try the blog? (*gulp*)
# ------- https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/
